### ISSUE TITLE
想问下，搭载了小雅的alist，配和alist.min.js的搜索，在tvbox搜索出来的电视剧，只能一集一集点击进去看，

### ISSUE THREAD

**Issue by qlql765** [hjdhnx/dr_py#11]
想问下，搭载了小雅的alist，配和alist.min.js的搜索，在tvbox搜索出来的电视剧，只能一集一集点击进去看，有没有办法搜索出来的电视剧，点击进去后，整部剧都显示
![1](https://github.com/hjdhnx/dr_py/assets/108382776/91be2112-4e16-4fff-9c6d-9d1c1a3414d7)
![2](https://github.com/hjdhnx/dr_py/assets/108382776/18964960-6f64-4fad-b2e3-3d9ba5c9c358)
![3](https://github.com/hjdhnx/dr_py/assets/108382776/020042a2-9883-45ab-b726-cbc5a3fa11b6)

**Comment by hjdhnx** [comment]
筛选条件有个单集/全集，你切换成全集后再去播放，就可以了

**Comment by qlql765** [comment]
> 筛选条件有个单集/全集，你切换成全集后再去播放，就可以了

感谢大佬的指点，已经可以了，谢谢
