### ISSUE TITLE
你好，写js源的时候能不能调试

### ISSUE THREAD

**Issue by Wirili** [hjdhnx/dr_py#12]
drpy2.js和util.ym.js 还是提示少local和req

**Comment by ihwf** [comment]
最新版本的在线日志连不上 websocket 了吗?

**Comment by zhizunbao84** [comment]
> 所有提示缺少的函数都是tvbox壳子内置的，包括 pdfh,pdfa,pd,pdfl,joinUrl,req,local.调试源请结合tvbox爱佬版壳子网页地址后面加/log进行看壳子在线运行源的日志

tvbox爱佬版，这是什么版本哦？

**Comment by ihwf** [comment]
其实会写 js 的可以直接参考👉 [CatVodOpen](https://github.com/catvod/CatVodOpen/tree/main/open)

**Comment by zhizunbao84** [comment]
> 其实会写 js 的可以直接参考👉 [CatVodOpen](https://github.com/catvod/CatVodOpen/tree/main/open)

CatVodOpen 我能看懂，但是这个drpy2.js 的写源我就有点迷糊
