### ISSUE TITLE
哔哩影视.js搜索结果不全

### ISSUE THREAD

**Issue by yonee77** [hjdhnx/dr_py#31]
哔哩影视 搜索名侦探柯南 只有前30个结果，后面的结果不显示，而是从第一个搜索结果开始无限循环显示，麻烦道长帮忙看一下。谢谢

**Comment by YuanHsing** [comment]
已经更新..搜索多页

你也可以试着去 官网搜索
https://search.bilibili.com/bangumi?keyword=名侦探柯南

看看结果是不是一样

最后建议你使用蜂蜜的影视TV

**Comment by yonee77** [comment]
> 

您好呀，最新版本我试了，不会循坏列表了，但是搜索结果比官网会少最后五个资源🙂

**Comment by yonee77** [comment]
> 已经更新..搜索多页
> 
> 你也可以试着去 官网搜索 [https://search.bilibili.com/bangumi?keyword=名侦探柯南](https://search.bilibili.com/bangumi?keyword=%E5%90%8D%E4%BE%A6%E6%8E%A2%E6%9F%AF%E5%8D%97)
> 
> 看看结果是不是一样
> 
> 最后建议你使用蜂蜜的影视TV

您好呀，最新版本我试了，不会循坏列表了，但是搜索结果比官网会少最后五个资源🙂
