### ISSUE TITLE
我写了一个量子资源采集站的js，希望能够过滤一些分类的搜索结果，但是目前有两个地方不知道如何去写，希望大佬能够指导一下

### ISSUE THREAD

**Issue by yutons** [hjdhnx/dr_py#41]
`var rule = {
    title: '01量子',
    host: 'https://cj.lzcaiji.com',
    homeUrl: '/api.php/provide/vod?ac=detail',
    detailUrl: '/api.php/provide/vod?ac=detail&ids=fyid',
    searchUrl: '/api.php/provide/vod?ac=detail&wd=**&pg=fypage',
    searchable: 2,//是否启用全局搜索,
    quickSearch: 0,//是否启用快速搜索,
    filterable: 0,//是否启用分类筛选,
    multi: 1,
    url: '/api.php/provide/vod?ac=detail&t=fyclass&pg=fypage&f=',
    class_name: '电影片&连续剧&综艺片&动漫片&动作片&喜剧片&爱情片&科幻片&恐怖片&剧情片&战争片&国产剧&香港剧',
    class_url: '1&2&3&4&6&7&8&9&10&11&12&13&14',
    timeout: 5000,
    limit: 20,
    推荐: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_pubdate',
    一级: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_pubdate',
    /**
     * TODO 问题1：
     * 资源采集站，二级链接如何解析？
     */
    二级: `json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_pubdate`,
    /**
     * TODO 问题2：
     * 资源采集站，此处如何使用js:方式实现数据解析
     * 目的：希望能够通过js:方式实现搜索结果过滤，过滤一些分类的搜索结果
     */
    搜索: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_pubdate',
}
`

**Comment by zhuyebo1** [comment]
大佬，这个可以用了吗
