### ISSUE TITLE
完善腾讯搜索结果

### ISSUE THREAD

**Issue by yonee77** [hjdhnx/dr_py#67]
搜索:'js:let d=[];pdfa=jsp.pdfa;pdfh=jsp.pdfh;pd=jsp.pd;let html=request(input);let baseList=pdfa(html,"body&&.result_item_v");baseList.forEach(function(it){let longText=pdfh(it,".result_title&&a&&Text");let shortText=pdfh(it,".type&&Text");let fromTag=pdfh(it,".result_source&&Text");let score=pdfh(it,".figure_info&&Text");let content=pdfh(it,".desc_text&&Text");let url=pdfh(it,".result_title&&a&&href");let img=pd(it,".figure_pic&&src");url="https://node.video.qq.com/x/api/float_vinfo2?cid="+url.match(/.*\\/(.*?)\\.html/)[1];log(shortText+"|"+url);if(fromTag.match(/腾讯/)){d.push({title:longText.split(shortText)[0],img:img,url:url,content:content,desc:shortText+" "+score})}});setResult(d);',

**Comment by hjdhnx** [comment]
大佬为啥不提pr
